export default {
    SAVE_USER_SUCCESS: "SAVE_USER_SUCCESS",
    LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
    DISABLE_REDIRECT: "DISABLE_REDIRECT",
    DISABLE_REDIRECT_LOGIN: "DISABLE_REDIRECT_LOGIN",
    STOP_SESSION: "STOP_SESSION",
    CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
    GET_VACATIONS_SUCCESS: "GET_VACATIONS_SUCCESS",
    REDIRECT_TO_LOGIN: "REDIRECT_TO_LOGIN",

};